# Generated by Django 5.1.2 on 2024-10-14 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Internship', 'Internship'), ('Freelance', 'Freelance'), ('Office-based', 'Office-based'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Project-based', 'Project-based')], default='Full time', max_length=50)),
                ('draft_created', models.DateTimeField(auto_now_add=True)),
                ('application_date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Interview appointed', 'Interview appointed'), ('Interviewed', 'Interviewed'), ('Offered', 'Offered'), ('Offer accepted', 'Offer accepted'), ('Rejected', 'Rejected')], default='Draft', max_length=50)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('application_method', models.CharField(blank=True, max_length=100, null=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
