# Generated by Django 5.1.2 on 2024-10-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
