# Generated by Django 5.1.2 on 2024-10-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_applications', '0002_alter_jobapplication_application_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='employment_type',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Contract', 'Contract'), ('Temporary', 'Temporary'), ('Internship', 'Internship')], default='Full time', max_length=50),
        ),
    ]
